server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 192.168.64.131
    username: leyou
    password: 123456
    virtual-host: /leyou
  redis:
    host: 192.168.64.131
leyou:
  sms:
    accessKeyId: LTAI4FqENS6cECdTgtgUaLGL # 你自己的accessKeyId
    accessKeySecret: r1PkCzUpINlTeuim1OgWGEyuFEkQfY # 你自己的AccessKeySecret
    signName: 乐优商城 # 签名名称
    verifyCodeTemplate: SMS_174170660 # 模板名称